source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AREndPointSwitch_Example', :exclusive => true do
  pod "AREndPointSwitch", :path => "../"
end

target 'AREndPointSwitch_Tests', :exclusive => true do
  pod "AREndPointSwitch", :path => "../"

  
end
